version: '2'
services:
  remote_user:
    image: quay.io/tamu_cpt/remote-user-proxy:latest
    links:
      - apollo:target
    ports:
      - "9998:80"
    environment:
      BACKEND_URL: "http://target:8080"
      REMOTE_USER: user@example.com
  apollo:
    image: quay.io/erasche/apollo:cpt
    links:
      - db
      - chado
    ports:
      - "8080:8080"
    environment:
      CONTEXT_PATH: ROOT
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db:5432/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado:5432/postgres"
    volumes:
      - "./data:/data"
  db:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      POSTGRES_PASSWORD: password
      INSTALL_CHADO_SCHEMA: "0"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  chado:
    image: erasche/chado:1.31-jenkins97-pg9.5
    environment:
      - POSTGRES_PASSWORD=password
      # The default chado image would try to install the schema on first run
      #- INSTALL_CHADO_SCHEMA=0
    volumes:
      - /var/lib/postgresql/9.4/
