version: '2'
services:
  apollo:
    image: quay.io/erasche/apollo:cpt
    #image: cpt-apollo
    links:
      - db
      - chado
    ports:
        - 8080
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"

      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado/postgres"
    volumes:
      - "./data:/data"
  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: password
  chado:
    image: erasche/chado:latest
    environment:
      - POSTGRES_PASSWORD=password
      # The default chado image would try to install the schema on first run
      #- INSTALL_CHADO_SCHEMA=0
    volumes:
      - /var/lib/postgresql/9.4/
